FROM node:20-alpine AS build

WORKDIR /app

# Prisma requires OpenSSL
RUN apk add --no-cache openssl

COPY package*.json ./

COPY prisma ./prisma

RUN npm install && npx prisma generate

COPY tsconfig.json ./

COPY src ./src

RUN npm run build


FROM node:20-alpine AS runtime

WORKDIR /app

# Prisma requires OpenSSL at runtime
RUN apk add --no-cache openssl

COPY package*.json ./

COPY prisma ./prisma

RUN npm install --omit=dev && npx prisma generate

COPY --from=build /app/dist ./dist

ENV NODE_ENV=production

EXPOSE 5000

CMD ["node", "dist/server.js"]